---
title: Curriculum Vitae
format:
  html: 
    css: css/cv.css
  docx: default
  # typst: 
  #   output-file: cv_typst.pdf
  #   papersize: a4
  #   margin: 
  #     bottom: .75in
  #hugo-md: default
  gfm:
    echo: false
    output-file: cv_gfm.md
  docusaurus-md:
    echo: false   
    output-file: cv_docusaurus.md
  cv-pdf: 
    title2: Thomas E. Gorman
    role: Cognitive Scientist
    output-file: tg_cv.pdf
    cvfooter:
      left: "Thomas Gorman"
      right: "[tegorman13@github.io](https://tegorman13.github.io)"
    cvcolor: 58748F #without `#`
    sectcolor: "701112"
    cvfont: tgcursor #texlive fonts like raleway,fetamont,gillius,comfortaa
    cvmeta:
      - left: Department of Psychological and Brain Sciences
        right:  "{{< fa globe >}} [tegorman13@github.io](https://tegorman13.github.io)"
      - title: 
        left: 1101 E. 10th St.
        right: "{{< fa brands github size=1.7x >}} [tegorman13](https://github.com/tegorman13)"
      - title: 
        left: Bloomington, IN 47405
        right: " {{< fa envelope >}} [tegorman@iu.edu](mailto:tegorman@iu.edu)"
execute:
  echo: false
  warning: false
format-links: [cv-pdf]
---


::: {.content-visible when-format="html"}
\
<p align="center"><a href="tg_cv.pdf" class="btn btn-primary"> {{< fa file-pdf >}} PDF Version</a></p>
\
:::


::: {.content-visible unless-format="pdf"}
::: {.content-visible unless-format="markdown"}
| <i class="fa fa-envelope" aria-hidden="true" title="An envelope"></i> [tegorman@iu.edu](mailto:tegorman@iu.edu) | <i class="fa fa-envelope" aria-hidden="true" title="An envelope"></i> [tegorman13@gmail.com](mailto:tegorman13@gmail.com) |
| --- | --- |
| <i class="ai ai-google-scholar" aria-hidden="true"></i> [Google Scholar](https://scholar.google.com/citations?user=USMVPjEAAAAJ&hl=en) | <i class="ai ai-orcid" aria-hidden="true"></i> [ORCiD](https://orcid.org/0000-0001-5366-5442) |
| <i class="fa fa-brands fa-github" aria-hidden="true" title="GitHub logo"></i> [GitHub](https://github.com/tegorman13) | <i class="ai ai-researchgate" aria-hidden="true"></i> [ResearchGate](https://www.researchgate.net/profile/Thomas-Gorman-3) |
:::
:::

\
\

## {{< fa university >}} Education

::: {.content-visible unless-format="pdf"}
::: {layout="[0.3, 0.7]"}
::: {#firstcol}
-   2017 - May 2024
:::

::: {#secondcol}
**Indiana University - Bloomington**\
- PhD in Psychology and Cognitive Science\
- Dissertation: *The Role of Variability in Learning Generalization: A Computational Modeling Approach*
:::

<div>
-   2011 - 2015
</div>

<div>

**University of Wisconsin – Madison**\
- B.Sc. in Psychology\
- Thesis: *Short-term mindfulness intervention reduces the negative attentional effects associated with heavy media multitasking*

</div>
:::
:::

::: {.content-visible when-format="pdf"}
```{=tex}
\begin{tabular}{p{0.3\textwidth} p{0.7\textwidth}}
2017 - May 2024 & \textbf{Indiana University - Bloomington} \\
& PhD in Psychology and Cognitive Science \\ 
& Dissertation: \textit{The Role of Variability in Learning Generalization: A Computational Modeling Approach}\\
2011 - 2015 & \textbf{University of Wisconsin - Madison} \\
& B.Sc. in Psychology \\
& Thesis: \textit{Short-term mindfulness intervention reduces the negative attentional effects associated with heavy media multitasking} \\
\end{tabular}
```
:::

\

## {{< fa chart-column >}} Experience

**Percepts and Concepts Lab**

-   PhD Student (2017 - Present)
-   Principal Investigator: Robert Goldstone, PhD

**Learning and Transfer Lab (University of Wisconsin-Madison)**

-   Lab Manager / Research Coordinator (2015-2017)
-   Undergraduate Research Assistant (2013 - May 2015)
-   Principal Investigator: C. Shawn Green, PhD

**Alexander Lab – Medical Physics (University of Wisconsin-Madison)**

-   Research Coordinator (2015 – 2017)
-   Principal Investigator: Andrew Alexander, PhD


**Center for Healthy Minds (University of Wisconsin-Madison)**

-   Undergraduate Research Assistant (January 2014 - May 2015)
-   Principal Investigator: Richard J. Davidson, PhD


\pagebreak

## {{< fa cogs >}} Skills

::: {.content-visible when-format="html"}
| Category | Skills |
| --- | --- |
| Programming | - R (Quarto, Rmarkdown, Shiny ) <br> - JavaScript <br> - Python (jupyter, torch, tensorflow) <br> - Bash (Shell scripting, Workflow automation) <br>  - MATLAB (psychtoolbox) |
| Computational Modeling| - Artificial Neural Networks <br> - Exemplar Models <br> - Bayesian Statistics <br> - Mixed Effect Models <br> - Similarity Scaling <br> - Approximate Bayesian Computation <br> - Individual Differences |
| Data Analysis  | - Multilevel Modeling <br> - Bayesian Statistics <br> - Mixed Effects Models <br> - Dimensionality Reduction <br> - Frequentist ANOVA/Regression <br> |
| Experimental Skills | - Behavioral Tasks <br> - Online Data Collection (jsPsych for web-based experiments) <br> - Survey Data Collection (Qualtrics) <br> - Mechanical Turk  <br> - MRI & EEG |
| Workflow Automation & Version Control | - Multi-language workflows (integrating R, Bash, Python) <br> - Git (Documentation, backup, branching, collaboration) |
| Tools | - RStudio <br> - VS Code <br> - Vim/Neovim <br> - Obsidian <br> |
| Miscellaneous Skills | - Web Scraping <br> - SQL  <br> - Website Design |

:::

::: {.content-visible unless-format="html"}

| Category | Skills |
| --- | --- |
| Programming | - R (Quarto, Rmarkdown, Shiny )  | 
|  | - JavaScript | 
|  | - Python (jupyter, torch, tensorflow) |  
|  | - Bash (Shell scripting, Workflow automation) |  
|  | - MATLAB (psychtoolbox) |
|  |
| Computational Modeling| - Artificial Neural Networks |
|  | - Bayesian Statistics | 
|  | - Mixed Effect Models | 
|  | - Dimensionality Reduction & Similarity Scaling | 
|  | - Approximate Bayesian Computation | 
|  | - Individual Differences |
|  |
| Data Analysis | - Multilevel Modeling |
|  | - Bayesian Statistics |
|  | - ANOVA; t-test; regression |
|  | - Mixed Effects Models |
|  | - Dimensionality Reduction |
|  |
| Experimental Skills | - Behavioral Tasks |
|  | - Online Data Collection (jsPsych for web-based experiments) |
|  | - Survey Data Collection (Qualtrics) |
|  | - Mechanical Turk |
|  | - MRI & EEG |
|  |
| Workflow Automation & Version Control | - Multi-language workflows (integrating R, Bash, Python) |
|  | - Git (Documentation, backup, branching, collaboration) |
|  |
| Tools | - RStudio |
|  | - VS Code |
|  | - Vim/Neovim |
|  |
| Miscellaneous Skills | - Web Scraping |
|  | - SQL |
|  | - Website Design |
:::
\

## {{< fa scroll >}} Journal Articles and Conference Proceedings

- **Gorman**, T. E., & Goldstone, R. L. (in progress). Impact of Training Variability on Visuomotor Function Learning
and Extrapolation. [link](https://tegorman13.github.io/htw/paper.html) 

-   **Gorman**, T. E., & Goldstone, R. L. (2022). An instance-based model account of the benefits of varied practice in visuomotor skill. *Cognitive Psychology*, *137*, 101491.

-   Bazyldo, A., Kecskemeti, S., Cochrane, A., **Gorman**, T., Rokers, B., Dean, D., Green, C. S., & Alexander, A. L. (2021). Assessment of R1 Relaxometry Changes Induced via Repeated Videogame Training as a Measure of Neuroplasticity in College-aged Brains. In Proceedings of the ISMRM & SMRT Annual Meeting & Exhibition. An Online Experience. [link](https://archive.ismrm.org/2021/1050.html)

-   Patrick, A., Dean, D., **Gorman**, T., Green, C. S., & Alexander, A. (2019). Assessment of Microstructural Changes Induced via Repeated Videogame Training as a Measure of Neuroplasticity in Normal Developing, College-age Brains. In Proceedings of the 27th Annual Meeting & Exhibition of the International Society for Magnetic Resonance in Medicine. Montréal, QC, Canada. [link](https://cds.ismrm.org/protected/19MProceedings/PDFfiles/3620.html)

-   Dean, C. D., Patrick, A. M., **Gorman**, T., Green, C. S., & Alexander, A. L. (2018). Neuroplastic Changes of Myelin Microstructure With Video Game Play. In Proceedings of the Joint Annual Meeting ISMRM-ESMRMB. Paris, France. [link](https://cds.ismrm.org/protected/18MProceedings/PDFfiles/0929.html)

-   Kattner, F., Cochrane, A., Cox, C. R., **Gorman**, T. E., & Green, C. S. (2017). Perceptual learning generalization from sequential perceptual training as a change in learning rate. *Current Biology*, *27*(6), 840-846.

-   **Gorman**, T.E., & Green, C.S. (2016). Short-term mindfulness intervention reduces the negative attentional effects associated with heavy media multitasking. *Scientific Reports*, *6*.

## {{< fa book >}} Reviews and Book Chapters

-   **Gorman**, T.E., Gentile, D.A., & Green, C.S. Problem gaming: a short primer (2018). *American Journal of Play*, *10* (3), 309-327

-   **Gorman**, T.E., & Green, C.S. (2017). Young minds on video games. In *Cognitive development in digital contexts*. 121-143. Academic Press. 

-   Green, C. S., **Gorman**, T., & Bavelier, D. (2016). Action Video-Game Training and Its Effects on Perception and Attentional Control. In *Cognitive Training* (pp. 107-116). Springer International Publishing.

## {{< fa comments >}} Presentations

-   Half Day Tutorial on Measuring Mindfulness Behaviorally: Onsite/Online Data Col-lection with jsPsych
    -   Cognitive Science Conference – 2018
-   Does interleaving go the distance? Exploring the effect of dissimilarity on interleaved category learning
    -   Math Psych/ICCM 2018
-   Short term mindfulness intervention reduces cognitive deficits in heavy media multi-taskers
    -   Undergraduate Research Symposium – UW-Madison – April 16th, 2015

## {{< fa award >}} Awards

IU-Bloomington – Development Training Grant – beginning Fall 2019

IU-Bloomington - Steinmetz Summer Research Award - 2018

UW-Madison - Undergraduate Research Scholar Award – 2015

UW-Madison - Hilldale Undergraduate/Faculty Research Fellowship – 2014

## {{< fa magnifying-glass >}} Ad-hoc Reviewer

Cognitive Science

Journal of Experimental Psychology: General

Journal of Experimental Psychology: Human Perception and Performance

Contemporary Educational Psychology

## {{< fa person-chalkboard >}} Conferences

Cognitive Science Conference - 2021

Cognitive Science Conference - 2018

Mathematical Psychology & ICCM 2018

Boston Meeting on Methods in Cognitive Training (NSF Sponsored) – May 2017