---
title: "Publications"
date: last-modified
linkcolor: "#1F407A"
---

<style>
  /* This will change the color of all links on this page */
  .content a {
    color: #701112; /* Replace #FF5733 with your desired color */
  }

  /* Optionally, you can add more styles for different link states */
  .content a:hover {
    color: #701112; /* Color when hovering over the link */
  }

  .content a:visited {
    color: #701112; /* Color for visited links */
  }
</style>


{{< iconify <icon> >}}
You can also check my [<u>Google Scholar page</u>](https://scholar.google.com/citations?user=USMVPjEAAAAJ&hl=en){target="_blank"} for an updated list of my works. 

-----


# Articles


Gorman, T. E., & Goldstone, R. L. (2022). An instance-based model account of the benefits of varied practice in visuomotor skill. *Cognitive Psychology*, *137*, 101491. [doi.org/10.1016/j.cogpsych.2022.101491](https://doi.org/10.1016/j.cogpsych.2022.101491) [ <iconify-icon inline="" icon="fa6-solid:file-lines"></iconify-icon>  <u><B>pdf</u></B>](pdf/Gorman_Goldstone_2022_Instance-based_model_varied_practice.pdf){target="_blank"}
\
\
Bazyldo, A., Kecskemeti, S., Cochrane, A., Gorman, T., Rokers, B., Dean, D., Green, C. S., & Alexander, A. L. (2021). Assessment of R1 Relaxometry Changes Induced via Repeated Videogame Training as a Measure of Neuroplasticity in College-aged Brains. In Proceedings of the ISMRM & SMRT Annual Meeting & Exhibition. An Online Experience. [link](https://archive.ismrm.org/2021/1050.html)
\
\
Patrick, A., Dean, D., Gorman, T., Green, C. S., & Alexander, A. (2019). Assessment of Microstructural Changes Induced via Repeated Videogame Training as a Measure of Neuroplasticity in Normal Developing, College-age Brains. In Proceedings of the 27th Annual Meeting & Exhibition of the International Society for Magnetic Resonance in Medicine. Montréal, QC, Canada. [link](https://cds.ismrm.org/protected/19MProceedings/PDFfiles/3620.html)
\
\
Dean, C. D., Patrick, A. M., Gorman, T., Green, C. S., & Alexander, A. L. (2018). Neuroplastic Changes of Myelin Microstructure With Video Game Play. In Proceedings of the Joint Annual Meeting ISMRM-ESMRMB. Paris, France. [link](https://cds.ismrm.org/protected/18MProceedings/PDFfiles/0929.html)
\
\
Kattner, F., Cochrane, A., Cox, C. R., Gorman, T. E., & Green, C. S. (2017). Perceptual learning generalization from sequential perceptual training as a change in learning rate. *Current Biology*, *27*(6), 840–846. [doi.org/10.1016/j.cub.2017.01.046](https://doi.org/10.1016/j.cub.2017.01.046)
[ <iconify-icon inline="" icon="fa6-solid:file-lines"></iconify-icon> <u><B>pdf</u></B>](pdf/Kattner_2017 _Perceptual_learning_generalization_from_sequential.pdf){target="_blank"}
\
\
Gorman, T. E., & Green, C. S. (2016). Short-term mindfulness intervention reduces the negative attentional effects associated with heavy media multitasking. *Scientific Reports*, *6*. [doi.org/10.1038/srep24542](https://doi.org/10.1038/srep24542) 
[ <iconify-icon inline="" icon="fa6-solid:file-lines"></iconify-icon>  <u><B>pdf</u></B>](pdf/Gorman_Green_2016_Short-term_mindfulness_intervention_reduces_the_negative_attentional_effects.pdf){target="_blank"}
\
\


# Review Papers & Book Chapters

Gorman, T. E., Gentile, D. A., & Green, C. S. (2018). Problem gaming: A short primer. *American Journal of Play*, 10(3), 309–327. 
[<iconify-icon inline="" icon="fa6-solid:file-lines"></iconify-icon> <u><B>pdf</u></B>](pdf/Gorman et al_2018_Problem_gaming.pdf){target="_blank"}
\
\
Gorman, T. E., & Green, C. S. (2017). Young minds on video games. In *Cognitive development in digital contexts* (pp. 121–143). Academic Press. 
\
\
Green, C. S., Gorman, T., & Bavelier, D. (2016). Action Video-Game Training and Its Effects on Perception and Attentional Control. In T. Strobach & J. Karbach (Eds.), *Cognitive Training* (pp. 107–116). Springer International Publishing.  [doi.org/10.1007/978-3-319-42662-4_10](https://doi.org/10.1007/978-3-319-42662-4_10)
[ <iconify-icon inline="" icon="fa6-solid:file-lines"></iconify-icon>  <u><B>pdf</u></B>](pdf/AVG_CognitiveTraining_Green_Gorman_Bavelier.pdf){target="_blank"}

\
\

-----

# Conference Presentations

Half Day Tutorial on Measuring Mindfulness Behaviorally: Onsite/Online Data Collection with jsPsych 
-Cognitive Science Conference – 2018

Does interleaving go the distance? Exploring the effect of dissimilarity on interleaved category learning 
-Math Psych/ICCM 2018

Short term mindfulness intervention reduces cognitive deficits in heavy media multi-taskers
-Undergraduate Research Symposium – UW-Madison – April 16th, 2015

-----


# Preprints


-----
