---
title: LBD project
---


# Project 3

b

# Test headers

blah blah

# Background

Last year, we applied to access data generated from the many popular online games by Lumos Labs (Lumosity). We received access to data from “Lost in Migration” a gamified version of the Eriksen Flanker task. Users are presented with a configuration of 5 “birds” - a central “target” bird and 4 “flanker” birds. The task is to indicate the direction of the central bird as fast as possible using the up/down/right/left arrow keys on their device. On 50% of trials, the flanker birds are pointing the same direction as the target birds, while on the other half of trials the flanker birds point in an incompatible direction. 

The total dataset consists of 8,551 individual users, 168,307 game sessions, and 8,207,980 trials of the game. A subset of the users in the dataset participated in a “split-test” conducted by Lumos Labs, wherein new users could be randomly assigned to one of several modified version of the game. The modified versions all increased the range of possible values for up to 3 aspects of the task stimuli: 
1) The rotation of the flanker birds relative to the target on incongruent trials (90,180,270 in standard version, continuous range in modified version)
2) The distance between flankers and target (constant in standard version), 
3) The size of the stimuli (constant in standard version)


## Proposed Analysis 1 {.tabset}

**Effect of split-test variability manipulation on learning** 1)
Residual Effect of Split-testvariation

-   After split-test users return to the standard version of LIM, for
    how long will we be able to detect behavioral differences between
    split-test and standard-only users (in terms of games and/or
    trials).

2)  Between-Group comparisons

-Standard version users vs. split test users during 'training' (Figure
3D)

-Standard vs. split-test on the first game after split test users switch
to standard version


Interaction with how many games split test users completed before
switching

-Higher varied vs. lower varied split test users

E.g'Flanker Size' users vs. 'Flanker Size & Rotation & Distance'
users.

## Proposed Analysis 2 {.tabset}

**Trial-by-trial influence of repetition and variability** Like many
in-lab experiments, the LIM trials are randomized. A consequence of this
randomization is that some users will experience a greater proportion of
repeat trials, while others.

Trial-by-trial variability

-   The total \# of unique configurations experienced

-   The distance between trials - in terms of properties of stimuli
(number, arrangement)

- Distance between a new trial, and all of the previously experienced
trials (or some window).



## References {.tabset}
